### ISSUE TITLE
Error in build if no locale specified

### ISSUE THREAD

**Issue by jimwormold** [dassencio/nmeagen#2]
Hi

I've just run the build script in a docker container and it failed with:
`
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1420: ordinal not in range(128)`

I think this is because I have no locale set. Adding the following encoding to the read() call fixes it. Not sure if it's the correct way but it works.

build:
`
ln90 with open("js/" + filename, encoding="utf-8") as js_file:`

Thanks for a great tool again!

**Comment by dassencio** [comment]
@jimwormold: Thank you for the bug report.

I added the fixes you suggested. If the problem persists, please let me know and I will take a second look at it.
